src/Entity/Lieu.php
<?php

namespace App\Entity;

use App\Repository\LieuRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=LieuRepository::class)
 */
class Lieu
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="text")
     */
    private $photo;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type;

    /**
     * @ORM\Column(type="text")
     */
    private $prix;

    /**
     * @ORM\Column(type="text")
     */
    private $horaires;

    /**
     * @ORM\Column(type="text")
     */
    private $adresse;

    /**
     * @ORM\Column(type="text")
     */
    private $transport;

    /**
     * @ORM\Column(type="text")
     */
    private $evenement;

    /**
     * @ORM\Column(type="text")
     */
    private $site_internet;

    /**
     * @ORM\Column(type="text")
     */
    private $lien_maps;

    /**
     * @ORM\Column(type="integer")
     */
    private $code_postal;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $VilleReferente;

    /**
     * @ORM\Column(type="boolean")
     */
    private $notre_selection;

    /**
     * @ORM\Column(type="boolean")
     */
    private $plus_visite;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getPrix(): ?string
    {
        return $this->prix;
    }

    public function setPrix(?string $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getHoraires(): ?string
    {
        return $this->horaires;
    }

    public function setHoraires(?string $horaires): self
    {
        $this->horaires = $horaires;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getTransport(): ?string
    {
        return $this->transport;
    }

    public function setTransport(?string $transport): self
    {
        $this->transport = $transport;

        return $this;
    }

    public function getEvenement(): ?string
    {
        return $this->evenement;
    }

    public function setEvenement(string $evenement): self
    {
        $this->evenement = $evenement;

        return $this;
    }

    public function getSiteInternet(): ?string
    {
        return $this->site_internet;
    }

    public function setSiteInternet(?string $site_internet): self
    {
        $this->site_internet = $site_internet;

        return $this;
    }

    public function getLienMaps(): ?string
    {
        return $this->lien_maps;
    }

    public function setLienMaps(string $lien_maps): self
    {
        $this->lien_maps = $lien_maps;

        return $this;
    }

    public function getCodePostal(): ?int
    {
        return $this->code_postal;
    }

    public function setCodePostal(int $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getVilleReferente(): ?string
    {
        return $this->VilleReferente;
    }

    public function setVilleReferente(string $VilleReferente): self
    {
        $this->VilleReferente = $VilleReferente;

        return $this;
    }

    public function getNotreSelection(): ?bool
    {
        return $this->notre_selection;
    }

    public function setNotreSelection(bool $notre_selection): self
    {
        $this->notre_selection = $notre_selection;

        return $this;
    }

    public function getPlusVisite(): ?bool
    {
        return $this->plus_visite;
    }

    public function setPlusVisite(bool $plus_visite): self
    {
        $this->plus_visite = $plus_visite;

        return $this;
    }
}

templates/pages/departement.html.twig
{% extends 'base.html.twig' %}
{% block title %}{{ departement.nom }} : Les villes {% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/bootsrtapcaroussel.min.css') }}">
    <link rel="stylesheet" href="{{ asset('css/stylenotreselection.css') }}">
{% endblock stylesheets %}

{% block javascripts %}
    <script src="{{ asset('js/popper.min.js') }}"></script>
    <script src="{{ asset('js/scriptnotreselection.js') }}"></script>
{% endblock javascripts %}

{% block body %}
    <main>
        <div class="bandeau d-flex justify-content-center flex-column align-items-center">
            <h1>{{ departement.nom }}</h1>
            <p>Voici les villes les plus cool du département !</p>
        </div>
        <div id="demo" class="carousel slide" data-ride="carousel">

            <!-- Indicators -->
            <ul class="carousel-indicators">
                <li data-target="#demo" data-slide-to="0" class="active"></li>
                <li data-target="#demo" data-slide-to="1"></li>
                <li data-target="#demo" data-slide-to="2"></li>
            </ul>

            <!-- The slideshow -->
            <div class="container carousel-inner no-padding">

                <div class="carousel-item active">

                    {% for ville in villes %}
                        {% if loop.index0 < 4 %}
                            <div class="col-xs-3 col-sm-3 col-md-3">
                                <a href="#image{{ ville.id }}"><img src="{{ ville.img }}" data-toggle="tooltip" alt="photo {{ ville.nom }}" title="{{ ville.nom }}" data-placement="top" data-animation="true"></a>
                            </div>
                        {% endif %}

                    {% endfor %}
                </div>


            </div>

            <!-- Left and right controls -->
            <a class="carousel-control-prev" href="#demo" data-slide="prev">
                <span class="carousel-control-prev-icon"></span>
            </a>
            <a class="carousel-control-next" href="#demo" data-slide="next">
                <span class="carousel-control-next-icon"></span>
            </a>
        </div>

        <!--Ligne de separation-->
        <div id="ligneSeparation"></div>

        <!--Renseignement sur les villes (Image/Descritpion/Map)-->
        <div class="container">
        {% for ville in villes %}

        <div class="slideIn fondBleu" id="">
            <a  href="{{path('app_home_ville',{ id: departement.codePostal ,ville: ville.nom }) }}">
            <div class="row d-flex justify-content-center">
                <div class="col-xs-3 col-sm-3 col-md-3 d-flex justify-content-center" id="image{{ville.id}}">
                    <img src="{{ville.img}}" alt="photo {{ ville.nom }}" id="imgTaille" height="100%">
                </div>
                <div class="col-xs-6 col-sm-6 col-md-6" id="textCentrer">
                    <h2>{{ville.nom}}</h2>
                    <p>{{ ville.description }}</p>
                </div>
                <div class="col-xs-3 col-sm-3 col-md-3" id="carte">
                    <iframe  src="{{ ville.lienMaps }}" width="100%" height="100%" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
                </div>
            </div>
            </a>
        </div>

        {% endfor %}
        </div>

        <div><a id="cRetour" class="cInvisible" href="#haut"></a></div>
    </main>
{% endblock body %}

templates/pages/les-plus-visite.html.twig
{% extends 'base.html.twig' %}
{% block title %}Les plus visités{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/bootsrtapcaroussel.min.css') }}">
    <link rel="stylesheet" href="{{ asset('css/stylenotreselection.css') }}">
{% endblock stylesheets %}

{% block javascripts %}
    <script src="{{ asset('js/popper.min.js') }}"></script>
    <script src="{{ asset('js/scriptnotreselection.js') }}"></script>
{% endblock javascripts %}

{% block body %}
    <main>
        <div class="bandeau d-flex justify-content-center flex-column align-items-center">
            <h1>Les plus visités</h1>
            <p>Ce que vous visitez le plus!</p>
        </div>
        <div id="demo" class="carousel slide" data-ride="carousel">

            <!-- Indicators -->
            <ul class="carousel-indicators">
                <li data-target="#demo" data-slide-to="0" class="active"></li>
                <li data-target="#demo" data-slide-to="1"></li>
                <li data-target="#demo" data-slide-to="2"></li>
            </ul>

            <!-- The slideshow -->
            <div class="container carousel-inner no-padding">

                <div class="carousel-item active">

                        {% for lieu in lieux %}
                            {% if loop.index0 < 4 %}
                                <div class="col-xs-3 col-sm-3 col-md-3">
                                    <a href="#image{{ lieu.id }}"><img src="{{ lieu.photo }}" data-toggle="tooltip" alt="photo {{ lieu.nom }}" title="{{ lieu.nom }}" data-placement="top" data-animation="true"></a>
                                </div>
                            {% endif %}

                        {% endfor %}
                </div>

                <div class="carousel-item">
                    {% for lieu in lieux %}
                        {% if loop.index0 > 3 and  loop.index0 <8 %}
                            <div class="col-xs-3 col-sm-3 col-md-3">
                                <a href="#image{{ lieu.id }}"><img src="{{ lieu.photo }}" data-toggle="tooltip" alt="photo {{ lieu.nom }}" title="{{ lieu.nom }}" data-placement="top" data-animation="true"></a>
                            </div>
                        {% endif %}
                    {% endfor %}

                </div>
                <div class="carousel-item">
                    {% for lieu in lieux %}
                        {% if loop.index0 > 7 and  loop.index0 <12 %}
                            <div class="col-xs-3 col-sm-3 col-md-3">
                                <a href="#image{{ lieu.id }}"><img src="{{ lieu.photo }}" data-toggle="tooltip" alt="photo {{ lieu.nom }}" title="{{ lieu.nom }}" data-placement="top" data-animation="true"></a>
                            </div>
                        {% endif %}
                    {% endfor %}

                </div>

            </div>

            <!-- Left and right controls -->
            <a class="carousel-control-prev" href="#demo" data-slide="prev">
                <span class="carousel-control-prev-icon"></span>
            </a>
            <a class="carousel-control-next" href="#demo" data-slide="next">
                <span class="carousel-control-next-icon"></span>
            </a>
        </div>

        <!--Ligne de separation-->
        <div id="ligneSeparation"></div>
        <div class=" container">
            <h2> Recherches par type :</h2>
        </div>
        <div class=" container d-flex flex-row justify-content-between flex-wrap">
            <div class="d-flex flex-column ">


                <div>
                    <label for="checkMusee">Musées : </label>
                    <input type="checkbox" id="checkMusee"  onclick="checkMusee()" checked>
                </div>
                <div>
                    <label for="checkPatrimoine">Patrimoine : </label>
                    <input type="checkbox" id="checkPatrimoine" onclick="checkPatrimoine()" checked>
                </div>
            </div>


            <div>
                <div >
                    <label for="checkCulture">Culture : </label>
                    <input type="checkbox" id="checkCulture" onclick="checkCulture()" checked>
                </div>
                <div>
                    <label for="checkShopping">Shopping : </label>
                    <input type="checkbox" id="checkShopping"  onclick="checkShopping()" checked>
                </div>
            </div>


            <div>
                <div>
                    <label for="checkParcs">Parcs : </label>
                    <input type="checkbox" id="checkParcs" onclick="checkParcs()" checked>
                </div>
                <div>
                    <label for="checkLoisirs">Loisirs : </label>
                    <input type="checkbox" id="checkLoisirs" onclick="checkLoisirs()" checked>
                </div>
            </div>


            <div>
                <div>
                    <label for="checkSite-naturel">Sites naturel : </label>
                    <input type="checkbox" id="checkSite-naturel" onclick="checkSiteNaturel()" checked>
                </div>
                <div>
                    <label for="checkGastronomie">Gastronomie : </label>
                    <input type="checkbox" id="checkGastronomie" onclick="checkGastronomie()" checked>
                </div>
            </div>
        </div>

        <!--Renseignement sur les villes (Image/Descritpion/Map)-->
        <div class="container">
            {% for lieu in lieux %}

                <div  class=" {{ lieu.type }} slideIn fondBleu" id="">
                    <a  href="{{path('app_home_lieu',{ id: lieu.codePostal ,ville: lieu.villeReferente, lieu: lieu.nom }) }}">
                        <div class="row d-flex justify-content-center">
                            <div class="col-xs-3 col-sm-3 col-md-3 d-flex justify-content-center" id="image{{lieu.id}}">
                                <img src="{{lieu.photo}}" alt="photo {{ lieu.nom }}" id="imgTaille" height="100%">
                            </div>
                            <div class="col-xs-6 col-sm-6 col-md-6" id="textCentrer">
                                <h2>{{lieu.nom}}</h2>
                                <p>{{ lieu.description }}</p>
                            </div>
                            <div class="col-xs-3 col-sm-3 col-md-3" id="carte">
                                <iframe  src="{{ lieu.lienMaps }}" width="100%" height="100%" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
                            </div>
                        </div>

                    </a>
                </div>

            {% endfor %}
        </div>
        <div><a id="cRetour" class="cInvisible" href="#haut"></a></div>
    </main>
{% endblock body %}

templates/pages/lieu.html.twig
{% extends 'base.html.twig' %}
{% block title %} {{ lieuEntier.nom}} : Les infos {% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/stylelieu.css') }}">
{% endblock stylesheets %}


{% block body %}
    <main>

        <div class="bandeau d-flex justify-content-center flex-column align-items-center">
            <h1 class="text-center">{{ lieuEntier.nom}}</h1>
            <p>{{ lieuEntier.type}}</p>
        </div>

        <div class="contenu">

            <div class="row d-flex justify-content-center">

                <div class="col-xl-5 blue bulleimages d-flex justify-content-center ml-0">
                    <img src="{{ lieuEntier.photo}}" alt="photo {{lieuEntier.nom}}" width="500px" class="img-fluid">
                </div>
                <div class="col-xl-1"></div>
                <div class="col-xl-5 blue bulle mr-0">
                    <h2>Description</h2>
                    <p>{{ lieuEntier.description}}</p>
                </div>

            </div>

            <div class="row  d-flex justify-content-center">

                <div class="col-xl-5 d-flex flex-wrap justify-content-between m-0 p-0">
                    <div class=" col-lg-3 col-md-5 col-sm-5 col-12 bulle white w-25 ml-0">
                        <h3>tarifs</h3>
                        <p>{{ lieuEntier.prix}}</p>
                    </div>

                    <div class=" col-lg-4 col-md-5 col-sm-5 col-12 bulle blue w-25">
                        <h3>Horaires</h3>
                        <p>{{ lieuEntier.horaires}}</p>
                    </div>


                    <div class=" col-lg-3 col-md-5 col-sm-5 col-12 bulle white w-25">
                        <h3>Adresse</h3>
                        <p>{{ lieuEntier.adresse}}</p>
                    </div>
                    <div class="  col-lg-3 col-md-5 col-sm-5 col-12 bulle blue w-25 ml-0">
                        <h3>Transports </h3>
                        <p>{{ lieuEntier.transport}}</p>
                    </div>


                    <div class=" col-lg-4 col-md-5 col-sm-5 col-12 bulle white w-25">
                        <h3>Evenements</h3>
                        <p>{{ lieuEntier.evenement}}</p>
                    </div>

                    <div class=" col-lg-3 col-md-5 col-sm-5 col-12 bulle blue w-25">
                        <h3>Site internet</h3>
                        <a href="{{ lieuEntier.SiteInternet}}" target="_blank">Accéder au site</a>
                    </div>
                </div>

                <div class="col-xl-1"></div>
                <div class="col-xl-5 bulleimages blue d-flex justify-content-center mr-0">
                    <iframe src="{{ lieuEntier.LienMaps }}" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
                </div>

            </div>

        </div>





    </main>
{% endblock body %}

templates/pages/notre-selection.html.twig
{% extends 'base.html.twig' %}
{% block title %}Notre séléction{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/bootsrtapcaroussel.min.css') }}">
    <link rel="stylesheet" href="{{ asset('css/stylenotreselection.css') }}">
{% endblock stylesheets %}

{% block javascripts %}
    <script src="{{ asset('js/popper.min.js') }}"></script>
    <script src="{{ asset('js/scriptnotreselection.js') }}"></script>
{% endblock javascripts %}

{% block body %}
    <main>
        <div class="bandeau d-flex justify-content-center flex-column align-items-center">
            <h1>Notre sélection</h1>
            <p>On sélectionne des lieux rien que pour toi !</p>
        </div>
        <div id="demo" class="carousel slide" data-ride="carousel">

            <!-- Indicators -->
            <ul class="carousel-indicators">
                <li data-target="#demo" data-slide-to="0" class="active"></li>
                <li data-target="#demo" data-slide-to="1"></li>
                <li data-target="#demo" data-slide-to="2"></li>
            </ul>

            <!-- The slideshow -->
            <div class="container carousel-inner no-padding">

                <div class="carousel-item active">

                    {% for lieu in lieux %}
                        {% if loop.index0 < 4 %}
                            <div class="col-xs-3 col-sm-3 col-md-3">
                                <a href="#image{{ lieu.id }}"><img src="{{ lieu.photo }}" data-toggle="tooltip" alt=" photo{{ lieu.nom }}" title="{{ lieu.nom }}" data-placement="top" data-animation="true"></a>
                            </div>
                        {% endif %}

                    {% endfor %}
                </div>

                <div class="carousel-item">
                    {% for lieu in lieux %}
                        {% if loop.index0 > 3 and  loop.index0 <8 %}
                            <div class="col-xs-3 col-sm-3 col-md-3">
                                <a href="#image{{ lieu.id }}"><img src="{{ lieu.photo }}" data-toggle="tooltip" alt="photo {{ lieu.nom }}" title="{{ lieu.nom }}" data-placement="top" data-animation="true"></a>
                            </div>
                        {% endif %}
                    {% endfor %}

                </div>
                <div class="carousel-item">
                    {% for lieu in lieux %}
                        {% if loop.index0 > 7 and  loop.index0 <12 %}
                            <div class="col-xs-3 col-sm-3 col-md-3">
                                <a href="#image{{ lieu.id }}"><img src="{{ lieu.photo }}" data-toggle="tooltip" alt="photo {{ lieu.nom }}" title="{{ lieu.nom }}" data-placement="top" data-animation="true"></a>
                            </div>
                        {% endif %}
                    {% endfor %}

                </div>

            </div>

            <!-- Left and right controls -->
            <a class="carousel-control-prev" href="#demo" data-slide="prev">
                <span class="carousel-control-prev-icon"></span>
            </a>
            <a class="carousel-control-next" href="#demo" data-slide="next">
                <span class="carousel-control-next-icon"></span>
            </a>
        </div>

        <!--Ligne de separation-->s
        <div id="ligneSeparation"></div>
        <div class=" container">
            <h2> Recherches par type :</h2>
        </div>
        <div class=" container d-flex flex-row justify-content-between flex-wrap">
            <div class="d-flex flex-column ">


                <div>
                    <label for="checkMusee">Musées : </label>
                    <input type="checkbox" id="checkMusee"  onclick="checkMusee()" checked>
                </div>
                <div>
                    <label for="checkPatrimoine">Patrimoine : </label>
                    <input type="checkbox" id="checkPatrimoine" onclick="checkPatrimoine()" checked>
                </div>
            </div>


            <div>
                <div >
                    <label for="checkCulture">Culture : </label>
                    <input type="checkbox" id="checkCulture" onclick="checkCulture()" checked>
                </div>
                <div>
                    <label for="checkShopping">Shopping : </label>
                    <input type="checkbox" id="checkShopping"  onclick="checkShopping()" checked>
                </div>
            </div>


            <div>
                <div>
                    <label for="checkParcs">Parcs : </label>
                    <input type="checkbox" id="checkParcs" onclick="checkParcs()" checked>
                </div>
                <div>
                    <label for="checkLoisirs">Loisirs : </label>
                    <input type="checkbox" id="checkLoisirs" onclick="checkLoisirs()" checked>
                </div>
            </div>


            <div>
                <div>
                    <label for="checkSite-naturel">Sites naturel : </label>
                    <input type="checkbox" id="checkSite-naturel" onclick="checkSiteNaturel()" checked>
                </div>
                <div>
                    <label for="checkGastronomie">Gastronomie : </label>
                    <input type="checkbox" id="checkGastronomie" onclick="checkGastronomie()" checked>
                </div>
            </div>
        </div>

        <!--Renseignement sur les villes (Image/Descritpion/Map)-->
        <div class="container">
        {% for lieu in lieux %}


                    <div  class=" {{ lieu.type }} slideIn fondBleu" id="">
                        <a  href="{{path('app_home_lieu',{ id: lieu.codePostal ,ville: lieu.villeReferente, lieu: lieu.nom }) }}">
                    <div class="row d-flex justify-content-center">
                        <div class="col-xs-3 col-sm-3 col-md-3 d-flex justify-content-center" id="image{{lieu.id}}">
                            <img src="{{lieu.photo}}" alt="photo {{ lieu.nom }}" id="imgTaille" height="100%">
                        </div>
                        <div class="col-xs-6 col-sm-6 col-md-6" id="textCentrer">
                            <h2>{{lieu.nom}}</h2>
                            <p>{{ lieu.description }}</p>

                        </div>
                        <div class="col-xs-3 col-sm-3 col-md-3" id="carte">
                            <iframe  src="{{ lieu.lienMaps }}" width="100%" height="100%" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
                        </div>
                    </div>

                </a>
                    </div>

        {% endfor %}
        </div>
        <div><a id="cRetour" class="cInvisible" href="#haut"></a></div>
    </main>
{% endblock body %}

templates/pages/ville.html.twig
{% extends 'base.html.twig' %}
{% block title %}{{ villeHome.nom}} : Les lieux{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/bootsrtapcaroussel.min.css') }}">
    <link rel="stylesheet" href="{{ asset('css/stylenotreselection.css') }}">
{% endblock stylesheets %}

{% block javascripts %}
    <script src="{{ asset('js/popper.min.js') }}"></script>
    <script src="{{ asset('js/scriptnotreselection.js') }}"></script>
    <script src="{{ asset('js/jquery.js') }}"></script>
{% endblock javascripts %}

{% block body %}
    <main>
        <div class="bandeau d-flex justify-content-center flex-column align-items-center">
            <h1>{{villeHome.nom}}</h1>
            <p>Voici les lieux les plus cool de cette ville!</p>
        </div>
        <div id="demo" class="carousel slide" data-ride="carousel">

            <!-- Indicators -->
            <ul class="carousel-indicators">
                <li data-target="#demo" data-slide-to="0" class="active"></li>
                <li data-target="#demo" data-slide-to="1"></li>
                <li data-target="#demo" data-slide-to="2"></li>
            </ul>

            <!-- The slideshow -->
            <div class="container carousel-inner no-padding">

                <div class="carousel-item active">

                    {% for lieu in lieux %}
                        {% if loop.index0 > 2 and  loop.index0 <7 %}
                            <div class="col-xs-3 col-sm-3 col-md-3">
                                <a href="#image{{ lieu.id }}"><img src="{{ lieu.photo }}" data-toggle="tooltip" alt="photo {{ lieu.nom }}" title="{{ lieu.nom }}" data-placement="top" data-animation="true"></a>
                            </div>
                        {% endif %}

                    {% endfor %}
                </div>

                <div class="carousel-item">
                    {% for lieu in lieux %}
                        {% if loop.index0 > 6 and  loop.index0 <11%}
                            <div class="col-xs-3 col-sm-3 col-md-3">
                                <a href="#image{{ lieu.id }}"><img src="{{ lieu.photo }}" data-toggle="tooltip" alt="photo {{ lieu.nom }}" title="{{ lieu.nom }}" data-placement="top" data-animation="true"></a>
                            </div>
                        {% endif %}
                    {% endfor %}

                </div>
                <div class="carousel-item">
                    {% for lieu in lieux %}
                        {% if loop.index0 > 10 and  loop.index0 <15 %}
                            <div class="col-xs-3 col-sm-3 col-md-3">
                                <a href="#image{{ lieu.id }}"><img src="{{ lieu.photo }}" data-toggle="tooltip" alt="photo {{ lieu.nom }} "title="{{ lieu.nom }}" data-placement="top" data-animation="true"></a>
                            </div>
                        {% endif %}
                    {% endfor %}

                </div>

            </div>

            <!-- Left and right controls -->
            <a class="carousel-control-prev" href="#demo" data-slide="prev">
                <span class="carousel-control-prev-icon"></span>
            </a>
            <a class="carousel-control-next" href="#demo" data-slide="next">
                <span class="carousel-control-next-icon"></span>
            </a>
        </div>

        <!--Ligne de separation-->
        <div id="ligneSeparation"></div>
        <div class=" container">
        <h2> Recherches par type :</h2>
        </div>
        <div class=" container d-flex flex-row justify-content-between flex-wrap">
            <div class="d-flex flex-column ">


                <div>
                    <label for="checkMusee">Musées : </label>
                     <input type="checkbox" id="checkMusee"  onclick="checkMusee()" checked>
                </div>
                <div>
            <label for="checkPatrimoine">Patrimoine : </label>
            <input type="checkbox" id="checkPatrimoine" onclick="checkPatrimoine()" checked>
                </div>
            </div>


            <div>
                <div >
            <label for="checkCulture">Culture : </label>
            <input type="checkbox" id="checkCulture" onclick="checkCulture()" checked>
                </div>
                <div>
            <label for="checkShopping">Shopping : </label>
            <input type="checkbox" id="checkShopping"  onclick="checkShopping()" checked>
                </div>
            </div>


            <div>
                <div>
            <label for="checkParcs">Parcs : </label>
            <input type="checkbox" id="checkParcs" onclick="checkParcs()" checked>
                </div>
                <div>
            <label for="checkLoisirs">Loisirs : </label>
            <input type="checkbox" id="checkLoisirs" onclick="checkLoisirs()" checked>
                </div>
            </div>


            <div>
                <div>
            <label for="checkSite-naturel">Sites naturel : </label>
            <input type="checkbox" id="checkSite-naturel" onclick="checkSiteNaturel()" checked>
                </div>
                <div>
            <label for="checkGastronomie">Gastronomie : </label>
            <input type="checkbox" id="checkGastronomie" onclick="checkGastronomie()" checked>
                </div>
            </div>
        </div>


        <!--Renseignement sur les villes (Image/Descritpion/Map)-->
        <div class="container">
            {% for lieu in lieux %}

                <div  class=" {{ lieu.type }} slideIn fondBleu" id="">
                    <a  href="{{path('app_home_lieu',{ id: lieu.codePostal ,ville: lieu.villeReferente, lieu: lieu.nom }) }}">
                        <div class="row d-flex justify-content-center">
                            <div class="col-xs-3 col-sm-3 col-md-3 d-flex justify-content-center" id="image{{lieu.id}}">
                                <img src="{{lieu.photo}}" alt="photo {{ lieu.nom }}" id="imgTaille" height="100%">
                            </div>
                            <div class="col-xs-6 col-sm-6 col-md-6" id="textCentrer">
                                <h2>{{lieu.nom}}</h2>
                                <p>{{ lieu.description }}</p>
                            </div>
                            <div class="col-xs-3 col-sm-3 col-md-3" id="carte">
                                <iframe  src="{{ lieu.lienMaps }}" width="100%" height="100%" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
                            </div>
                        </div>

                    </a>
                </div>

            {% endfor %}
        </div>
        <div><a id="cRetour" class="cInvisible" href="#haut"></a></div>
    </main>
{% endblock body %}